[package]
name = "mediathek"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
adw = { package = "libadwaita", version = "0.5", features = ["v1_4"] }
ashpd = "0.6.2"
const_format = "0.2.31"
enumflags2 = "0.7.8"
eyre = "0.6.8"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gsettings-macro = "0.1.19"
gtk = { version = "0.7.3", package = "gtk4", features = ["gnome_45", "blueprint"] }
gvdb-macros = "0.1.10"
indexmap = { version = "2.0.2", features = ["serde"] }
mediathekviewweb = { version = "0.1.2", path = "../mediathekviewweb-rs" }
once_cell = "1.18.0"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
strum = { version = "0.25.0", features = ["derive"] }
time = { version = "0.3.29", features = ["parsing", "serde"] }
tokio = { version = "1.32.0", features = ["time", "rt-multi-thread", "macros"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
