# SPDX-FileCopyrightText: d-k-bo <d-k-bo@mailbox.org>
# SPDX-License-Identifier: CC0-1.0

name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install meson & dependencies
        run: sudo apt-get install -y meson gettext libglib2.0-bin libgtk-4-bin desktop-file-utils
      - name: Create meson dist bundle
        run: meson setup _build && meson dist -C _build --no-tests
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: _build/meson-dist/*
